### ISSUE TITLE
Home page, About and About this Site

### ISSUE THREAD

**Issue by meatballs** [Ventilator-Python/website#2]
I think the content that is currently under 'About this site' would be better on the home page. 'About this site' could then be removed.

'About Us' should probably be renamed to 'Community' and have some content explaining who wer are and how to get involved.

**Comment by belteki** [comment]
Will do

**Comment by meatballs** [comment]
I'm happy to pick this up - mucking about with the home page is not as simple as other pages.

**Comment by belteki** [comment]
Thanks for sorting it out.
